name: register-artifact-from-github
on:
    push
jobs:
    register-artifact:
      name: Register build artifact
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      outputs:
        artifact_id: ${{ steps.register-build-artifact.outputs.cbp_artifact_id }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - name: Build
          run: |
            sleep 10
        - id: register-build-artifact
          name: Register build artifact
          uses: cloudbees-io-gha/register-build-artifact@v3
          with:
            cloudbees-url: "https://api.saas-qa.beescloud.com"
            name: h-artifact-gha-bb
            url: "https://example.com/h-artifact-gha/1.0.0"
            version: 1.0.0
        - run: |
            echo '${{ steps.register-build-artifact.outputs.cbp_artifact_id }}'
          name: Print artifact id

    deploy-artifact:
      name: Deploy artifact to QA
      runs-on: ubuntu-latest
      needs: register-artifact
      permissions:
        id-token: write
        contents: read
      steps:
        - name: Checkout code
          uses: actions/checkout@v6
        - name: Deploy to QA
          run: |
            echo "Deploying artifact ${{ needs.register-artifact.outputs.artifact_id }} to QA environment"
            sleep 5
        - uses: docker://public.ecr.aws/cloudbees/actions/gha-register-deployed-artifact:main-8d819ee6c37734d240bc3e399c7515d85aa14f76
          name: Register deployed artifact
          id: register-deployed-artifact
          env:
            CLOUDBEES_API_URL: "https://api.saas-qa.beescloud.com"
            TARGET_ENVIRONMENT: "QA"
            ARTIFACT_ID: ${{ needs.register-artifact.outputs.artifact_id }}
            DEPLOYMENT_LABELS: "test"